services:
  assistant_service:
    build: .
    restart: always
    depends_on:
      assistant_cache:
        condition: service_started
    profiles:
      - assistant
      - all

  assistant_cache:
    image: redis:7.2.4-alpine
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    profiles:
      - assistant
      - all

  assistant_nginx:
    image: nginx:1.25.4
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - assistant_service
    ports:
      - "81:81"
    profiles:
      - assistant
      - all
