name: Python Package

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}


      - name: Install Poetry
        run: |
          cd assistant
          python -m pip install --upgrade pip
          pip install poetry
          poetry install


      - name: Create folder for report
        run: |
          mkdir -p reports/wemake-python-styleguide/
          mkdir -p reports/mypy/


      - name: Run mypy
        run: |
          cd assistant
          poetry run mypy --ignore-missing-imports . --html-report reports/mypy/ || true


      - name: Run flake8
        run: |
          cd assistant
          poetry run flake8 --config=setup.cfg --format=html --htmldir=reports/wemake-python-styleguide/ --exit-zero


      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.python-version }}
          path: reports/